# -*- coding: utf-8 -*-
"""Qr_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGZRHAxMELuleHfW85gCCuP1ZwYob2Se

#**Create a Qr Code**
"""

pip install 'qrcode[pil]'

import qrcode as qr

img=qr.make("https://github.com/AnshulKumar001")

img.save("GitHub_Link.png")